[project]
name = "riscv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CENTAURUSGOD", email = "ozonewagle998@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplot>=0.1.9",
    "numpy>=2.5.2",
    "ruff>=0.16.6",
    "scipy>=1.18.1",
]
