[project]
name = "riscv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CENTAURUSGOD", email = "ozonewagle998@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplot>=0.1.9",
    "numpy>=2.5.2",
    "scipy>=1.18.1",
]

[project.scripts]
riscv = "riscv:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
