import scipy.io.wavfile as wav
import numpy as np

# Audio configuration (matching 10 kHz sample rate from signal generation)
sample_rate = 10000
output_samples = []

# Read hex file generated by Icarus Verilog testbench
with open("single_lf.hex", "r") as f:
    for line in f:
        hex_str = line.strip()
        if not hex_str:
            continue
        
        # Parse 16-bit unsigned hex value
        val = int(hex_str, 16)
        
        # Convert two's complement unsigned (0x0000-0xFFFF) to signed (-32768 to 32767)
        if val >= 0x8000:
            val -= 0x10000
            
        output_samples.append(val)

# Convert to 16-bit signed numpy array
audio_data = np.array(output_samples, dtype=np.int16)

# Save filtered audio signal
wav.write("single_lpf_accelerator_output.wav", sample_rate, audio_data)
print(f"Successfully converted {len(audio_data)} samples to 'single_lpf_accelerator_output.wav'.")