import numpy as np
import scipy.io.wavfile as wav


def convert_hex_to_wav(hex_filename, wav_filename, sample_rate=10000):
    output_samples = []

    # Read hex file generated by Icarus Verilog testbench
    with open(hex_filename, "r") as f:
        for line in f:
            hex_str = line.strip()
            if not hex_str:
                continue

            # Parse 16-bit unsigned hex value
            val = int(hex_str, 16)

            # Convert two's complement unsigned (0x0000-0xFFFF) to signed (-32768 to 32767)
            if val >= 0x8000:
                val -= 0x10000

            output_samples.append(val)

    # Convert to 16-bit signed numpy array
    audio_data = np.array(output_samples, dtype=np.int16)

    try:
        if wav_filename is None:
            wav_filename = hex_filename.replace(".hex", ".wav")

        # Save filtered audio signal
        wav.write(wav_filename, sample_rate, audio_data)
        print(f"Successfully converted {len(audio_data)} samples to '{wav_filename}'.")
    except Exception as e:
        print(f"Error saving WAV file '{wav_filename}': {e}")


# Change the input and output filenames as needed
convert_hex_to_wav("audio_out.hex", "output_audio.wav", sample_rate=10000)
