module control_unit (
    input [6:0] opcode,

    output reg branch,
    output reg  mem_read,
    output reg mem_to_reg,
    output reg [1:0] alu_op,
    output reg mem_write,
    output reg alu_src,
    output reg reg_write
);

    always @(*) begin
        case (opcode)
        // r type
            7'b0110011 : begin
                alu_src = 1'b0;
                mem_to_reg = 1'b0;
                reg_write = 1'b1;
                mem_read = 1'b0;
                mem_write = 1'b0;
                branch = 1'b0;
                alu_op = 2'b10;
            end

            // immediate instructions liek addi x1, x0, 25
            7'b0010011: begin
                alu_src = 1'b1;
                mem_to_reg = 1'b0;
                reg_write = 1'b1;
                mem_read = 1'b0;
                mem_write = 1'b0;
                branch = 1'b0;
                // confused here
                // as immediate value is already generated by imm_data_gen, 
                // operation should be same as r type

                // sept 1 changing alu_op from 2'b10 to 2'b00 to see if it works
                alu_op = 2'b00;
            end

            // don't know what below are
            // maybe following lab, i chosed for 64 bit

            // I-type Load
            7'b0000011 : begin
                alu_src = 1'b1;
                mem_to_reg = 1'b1;
                reg_write = 1'b1;
                mem_read = 1'b1;
                mem_write = 1'b0;
                branch = 1'b0;
                alu_op =  2'b00;
            end

            // I-type Store
            7'b0100011 : begin
                alu_src = 1'b1;
                mem_to_reg = 1'bx;
                reg_write = 1'b0;
                mem_read = 1'b0;
                mem_write = 1'b1;
                branch = 1'b0;
                alu_op =  2'b00;
            end
            // B Type
            7'b1100011 : begin
                alu_src = 1'b0;
                mem_to_reg = 1'bx;
                reg_write = 1'b0;
                mem_read = 1'b0;
                mem_write = 1'b0;
                branch = 1'b1;
                alu_op =  2'b01;
            end
            // U Type
            7'b0110111 : begin
                // eg. lui instruction
                // carefully place what to use here
                alu_src = 1'b1; // 1: selects immediate data generator
                mem_to_reg = 1'b0;
                reg_write = 1'b1; // writting upper immedia to reg ro 1?
                mem_read = 1'b0;
                mem_write = 1'b0;
                branch = 1'b0;
                alu_op =  2'b00;  
            end
            default: begin
                alu_src = 1'b0;
                mem_to_reg = 1'b0;
                reg_write = 1'b0;
                mem_read = 1'b0;
                mem_write = 1'b0;
                branch = 1'b0;
                alu_op = 2'b00;
            end
        endcase
    end
    
endmodule